# Generated by Django 2.2.13 on 2020-10-24 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='who_likes',
            field=models.ManyToManyField(related_name='photos_users', to=settings.AUTH_USER_MODEL, verbose_name='who_likes'),
        ),
    ]
